# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
# TODO: Need to move all these out to the common Makefile
ARDUINO_DIR   = /Applications/Arduino.app/Contents/Java
ARDMK_DIR     = /usr/local/opt/arduino-mk/
ARDUINO_LIBS = Cytron_Maker_Sumo_Library EEPROM Servo
BOARD_TAG    = uno
include ../../MonitorPort.mk
include $(ARDMK_DIR)/Arduino.mk
